branch-defaults:
  default:
    environment: flask-tutorial1-env
    group_suffix: null
environment-defaults:
  flask-tutorial-env:
    branch: null
    repository: null
global:
  application_name: flask-tutorial1
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
